### PR TITLE
Code column wasn't always at top of browser window in multi-column view

### LINKED ISSUE #2307: Code block does not show the file content consistently
In single pane or mobile view, clicking on the code block to show the file content doesn't work consistently or didn't work after first use

- visit https://openliberty.io/guides/docker.html
- reduce the browser size to show single pane 
- scroll down to https://openliberty.io/guides/docker.html#getting-started
- click the green box 
Screen Shot 2021-10-14 at 4 56 25 PM
- code text pane show up as 
Screen Shot 2021-10-14 at 4 57 13 PM
- click "Back to text"
- click the green box again
- a flash happens and code text pane does not show up
- the content cannot be scrolled anymore
- after resize the window a little, the text pane shows up again

### PR DESCRIPTION
**Pull request by erica-banda-03**
#### Were the changes tested on
- [x] Firefox (Desktop)
- [x] Safari (Desktop)
- [x] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)
#### Running validation tools
- [ ] https://validator.w3.org/checklink
- [ ] https://validator.w3.org
- [x] Dymanic Accessability Plugin (DAP) -- now IBM Equal Access Accessibility Checker
- [ ] Lighthouse (in Chrome dev tools)

### CODE REVIEW

File: src/main/content/_assets/js/openliberty.js [hunk 1]
```diff
@@ -116,7 +116,15 @@ var openliberty = (function() {
             $("#toc_inner").css("margin-top", "0px");
         }
         $("#toc_indicator").css("margin-top", "0px");
-        $("#code_column").css({"position":"fixed"})
+
+        //handles where the top of the code column should be
+        if (!inSingleColumnView()) {
+            //below the hotspot in single column view
+            $("#code_column").css({"position":"fixed", "top":"0px"})
```
Comment (steven1046) [inline src/main/content/_assets/js/openliberty.js:123]: Should the comments be switched since the first one is not in single column?

Comment (erica-banda-03) [reply src/main/content/_assets/js/openliberty.js:123]: Yup 🤦‍♀️ Fixing now.

**Review by steven1046 — APPROVED** [review]
